// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sythqwoldifsrwajvemn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dGhxd29sZGlmc3J3YWp2ZW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDExMDUsImV4cCI6MjA2OTE3NzEwNX0.Jl19wVNaiiy00XbKiiWwAPRnLtorUpZE0zH0RIbVfcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);