// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dqozhtqgwzkuzvqfchdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxb3podHFnd3prdXz2cWZjaGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzE3OTMsImV4cCI6MjA3MTg0Nzc5M30.Vf9zu9LkEkW58Y84lidjU2iPJUYE0F65Fq0heYMMT2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);